#include "levels/castle_grounds/areas/1/custom/1/model.inc.c"
#include "levels/castle_grounds/areas/1/custom/2/model.inc.c"
#include "levels/castle_grounds/areas/1/custom/3/model.inc.c"
#include "levels/castle_grounds/areas/1/custom/4/model.inc.c"
#include "levels/castle_grounds/areas/1/custom/5/model.inc.c"
#include "levels/castle_grounds/areas/1/custom/6/model.inc.c"
#include "levels/castle_grounds/areas/1/custom/7/model.inc.c"
#include "levels/castle_grounds/areas/1/custom/8/model.inc.c"
#include "levels/castle_grounds/areas/1/custom/9/model.inc.c"

#include "levels/castle_grounds/areas/1/custom/collision.inc.c"
