#include "levels/castle_courtyard/areas/1/custom/texture.inc.c"
#include "levels/castle_courtyard/areas/1/custom/1/model.inc.c"
#include "levels/castle_courtyard/areas/1/custom/2/model.inc.c"
#include "levels/castle_courtyard/areas/1/custom/3/model.inc.c"
#include "levels/castle_courtyard/areas/1/custom/collision.inc.c"
